[package]
name = "windexer-jito-staking"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
# Internal crates
windexer-common = { path = "../windexer-common" }
chrono = "0.4"

# Solana dependencies
solana-sdk = { workspace = true }
solana-program = { workspace = true }

# Workspace dependencies
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
thiserror = "2.0"
tracing-subscriber = { workspace = true }

[[bin]]
name = "windexer-jito-staking"
path = "src/main.rs"