[workspace]
resolver = "2"
members = [
    "crates/windexer-api",
    "crates/windexer-common",
    "crates/windexer-geyser", 
    "crates/windexer-jito-staking",
    "crates/windexer-network",
    "crates/windexer-store"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Vivek <31vivekpal@gmail.com>"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# Solana ecosystem - aligned versions to avoid conflicts
solana-sdk = "2.1.11"
solana-program = "2.1.11"
solana-geyser-plugin-interface = "1.18.0"
solana-transaction-status = "2.1.11"
spl-token = "7.0.0"
spl-token-2022 = "7.0.0"
solana-zk-token-sdk = "2.1.11"

# Network stack
libp2p = { version = "0.55.0", features = [
    "tcp",
    "dns", 
    "websocket",
    "noise",
    "yamux",
    "gossipsub",
    "mdns",
    "tokio"
] }
tokio = { version = "1.32", features = ["full"] }
tokio-tungstenite = "0.26.1"
tungstenite = "0.26.1"

# Database functionality
sqlx = { version = "0.8.3", default-features = false, features = [
    "runtime-tokio-native-tls",
    "postgres",
    "macros"
] }

# Cryptography
sha2 = "0.10"
ed25519-dalek = "2.0"

# Common utilities
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
anyhow = "1.0.95"
thiserror = "2.0.11"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
bytes = "1.5.0"
futures = "0.3.28"
async-trait = "0.1.74"
chrono = "0.4"

[patch.crates-io]
aes-gcm-siv = { git = "https://github.com/RustCrypto/AEADs", rev = "6105d7a5591aefa646a95d12b5e8d3f55a9214ef" }
curve25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek.git", rev = "c14774464c4d38de553c6ef2f48a10982c1b4801" }
subtle = { git = "https://github.com/dalek-cryptography/subtle", tag = "2.4.0" }
