[workspace]
resolver = "2"
members = [
    "crates/windexer-api",
    "crates/windexer-common",
    "crates/windexer-geyser", 
    "crates/windexer-jito-staking",
    "crates/windexer-network",
    "crates/windexer-store"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
solana-sdk = "2.1.11"
solana-program = "2.1.11"
solana-geyser-plugin-interface = "1.18.26"

sqlx = { version = "0.8.3", default-features = false, features = ["runtime-tokio-native-tls", "postgres", "macros"] }

libp2p = { version = "0.55.0", features = ["tcp", "dns", "websocket", "noise", "yamux", "gossipsub", "mdns"] }
tokio = { version = "1.32", features = ["full"] }

tracing = "0.1.41"
tracing-subscriber = "0.3.19"
anyhow = "1.0.95"
thiserror = "2.0.11"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
bytes = "1.5.0"
futures = "0.3.28"
async-trait = "0.1.74"

[patch.crates-io]
# Explicitly pin zeroize to resolve version conflict
zeroize = { version = "=1.8.1" }  # Use the latest version from the error list

# Keep your existing git patches
aes-gcm-siv = { git = "https://github.com/RustCrypto/AEADs", rev = "6105d7a5591aefa646a95d12b5e8d3f55a9214ef" }
curve25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek.git", tag = "curve25519-4.1.1" }