services:
  windexer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9100:9100"
    environment:
      - RUN_MODE=production
      - RUST_LOG=info
      - REDIS_URL=redis://redis:6379
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SOLANA_WS_URL=${SOLANA_WS_URL}
    depends_on:
      - redis
      - scylla
      - clickhouse

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: