[package]
name = "windexer-common"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
# Solana dependencies
solana-sdk = { workspace = true }
solana-program = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Async utilities
tokio = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }

# Logging
tracing = { workspace = true }

# Time handling and cryptography
chrono = { workspace = true, features = ["serde"] }
sha2 = { workspace = true }

# Utilities
bytes = { workspace = true }
bs58 = "0.5"