[package]
name = "windexer-network"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
# Internal crates
windexer-common = { path = "../windexer-common" }

# Network dependencies
libp2p = { version = "0.55.0", features = ["tokio", "tcp", "noise", "gossipsub", "mdns", "yamux"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

# Error handling & logging 
anyhow = "1.0"
thiserror = "2.0.11"
tracing = "0.1"

[dev-dependencies]
tokio-test = "0.4"