[solana]
rpc_url = "https://api.mainnet-beta.solana.com"
ws_url = "wss://api.mainnet-beta.solana.com"

[database]
host = "scylla"
port = 9042
keyspace = "windexer"

[api]
port = 8080

[metrics]
port = 9100