[package]
name = "windexer-geyser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Internal crates
windexer-common = { path = "../windexer-common" }
windexer-network = { path = "../windexer-network" }

# Solana dependencies
solana-geyser-plugin-interface.workspace = true
solana-sdk.workspace = true

# Workspace dependencies
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
tracing.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]