[package]
name = "windexer-geyser"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
# Internal crates
windexer-common = { path = "../windexer-common" }
windexer-network = { path = "../windexer-network" }

# Solana dependencies - use exact versions
solana-sdk = "=1.18.26"
solana-program = "=1.18.26"

# Workspace dependencies
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
