apiVersion: apps/v1
kind: Deployment
metadata:
  name: windexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windexer
  template:
    metadata:
      labels:
        app: windexer
    spec:
      containers:
      - name: windexer
        image: your-registry/windexer:latest
        ports:
        - containerPort: 8080
        - containerPort: 9100
        env:
        - name: RUN_MODE
          value: "production"
        - name: RUST_LOG
          value: "info"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: SOLANA_RPC_URL
          valueFrom:
            secretKeyRef:
              name: solana-secrets
              key: rpc-url
        - name: SOLANA_WS_URL
          valueFrom:
            secretKeyRef:
              name: solana-secrets
              key: ws-url